### PR TITLE
Issue #263 & Upasana's issue #1

### PR DESCRIPTION
**Pull request by Sweet-kid**
Hi,
As of now, I think I am done, I may add some more things on sunday evening (depending on the internet).
Please review it & let me know if I need to change anything.
Thanks so much in advance.

### CODE REVIEW

**Comment by Sweet-kid** [comment]
Sadly, I am unable to run tests because installation of XML::Feed failed because of one of the dependencies. I will look at it later in the day, too tired to do it right now.
Sorry for submitting PR without running tests.

**Comment by szabgab** [comment]
Thanks!

Don't worry about not running the tests. You are not expected to. (Though it would be still nice if you could figure out what's wrong with the dependencies and fix them 😄 )

What you can do to check your file is run `perl bin/generate.pl web all` to see if that properly generates the html files and the rss feed. (There you can check if the process ends sucessfully and then you could look at the results by launching `plackup` and browsing to http://127.0.0.1:5000/ .

The issues I found: and don't worry, the second time you will have much less of these 😄 


* The blogspot URLs should end with .com (This requirement is a recent change I made: blogspot has local URLs in every country so when you visit site.blogspot.com it will automatically redirect to site.blogspot.CC (Where CC is the country you are browsing from.) In order to avoid having blospot links all over the world, I've replaced all the blogspot.CC by blogspot.com and added a check that will make sure we use only .com
* Once I've fixed the blogspot URLs and tried to generate the html again it started to complain about the 'Portable GitHub... ' entry. Apparently in JSON the values need to be within double quotes and internally, if you'd like to use double-quotes you need to escape them.

* There was a left-over comma on the line that only contains your name. (JSON does not accept trailing comma on the last item in a hash.)

* vikas_kumar, tobias_oetiker, perlancar, and a few others are not in the authors.json - please update that file too or check if those people are already there with some other key. (e.g. perlancar is steven_haryanto )

* If you fixed all that you'll get a 'Use of uninitialized value in hash element at' warning that was caused by the 'editor' entry being upasana instead of 'upasana_shukla' as it is in the json file.
Since then I've fixed the perl code to give the proper error message there.

* Instead of upper case 'PLEASE SUBMIT YOUR TALKS' I think it would be better to make that bold by writing <b>Please, submit your talks</b>. (Most people read the HTML version of the newsletter)

**Comment by Sweet-kid** [comment]
Hi @szabgab 
Thanks for the review. 
I managed to install XML::Feed. I have revised my PR, please review it.

**Comment by szabgab** [comment]
Looks good. Thanks.
I'll merge it later. Just next time, please only commit and push the source json files and not the generated files.

**Comment by Sweet-kid** [comment]
Ok, I will make sure to do one commit in future.
Thanks a bunch for the review.

**Pull request merged**
