### PR TITLE
Issue 344

### PR DESCRIPTION
**Pull request by GeekRuthie**

### CODE REVIEW

**Comment by szabgab** [comment]
thanks

**Comment by szabgab** [comment]
Oh, but no subject and no intro. I'll write them.

**Comment by GeekRuthie** [comment]
Crap!  Can't believe I forgot that.  Yesterday was a rough day...  :(

**Comment by szabgab** [comment]
No worries, it gives me an opportunity to rant about my flight that got  lost in the cloud...

**Pull request merged**
