### PR TITLE
Some copyediting

### PR DESCRIPTION
**Pull request by davorg**

### CODE REVIEW

**Comment by szabgab** [comment]
thanks

**Comment by szabgab** [comment]
And I am glad you caught these before I sent out the email. Maybe we can have a tradition of this :)

**Comment by davorg** [comment]
I'd like to help more regularly, but I don't always have the time. And you usually send the email out sooo early :-)

**Comment by szabgab** [comment]
I'll start postponing it to give you a chance, or you could just get up at 5 am for this :smile:

**Pull request merged**
