### PR TITLE
First draft for issue #356.

### PR DESCRIPTION
**Pull request by manwar**
Hi Gabor,

Please review the draft for next edition of Perl Weekly newsletter.
As this is my first edition, I will be better prepared with more juicy stuff next time.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by szabgab** [comment]
Looks good so far. I hope you plan to update the PR Sunday evening with all the content you'd like to include.

**Comment by manwar** [comment]
Certainly, I will do one final push by Sunday evening :-)

**Comment by manwar** [comment]
Hi Gabor,

I have added some more contents. 
Please review the changes. 
I don't have any thing else to add to it.

Many Thanks.
Best Regards,
Mohammad S Anwar

**Comment by szabgab** [comment]
thanks, I'll do the rest myself

**Pull request merged**
