### PR TITLE
Add an index.rss feed

### PR DESCRIPTION
**Pull request by davorg**
Fixes https://github.com/szabgab/perlweekly/issues/368

Adds another option to `generate.pl` which generates another RSS file that works in the way described in the issue linked above.

    $ ./generate.pl indexrss latest

Or

    $ ./generate indexrss [issue-number]

The new file is `docs/index.rss`.

I tried to stick with your coding style, but it's possible you'll want to tweak some stuff.

### CODE REVIEW

**Comment by davorg** [comment]
This will be back later today :-)

**Comment by matthewpersico** [comment]
What will be back?

**Comment by davorg** [comment]
The pull request. I foolishly didn't create a separate branch for it, so when I did my next copy-edit, it would have pulled that in too if I hadn't had closed this PR first.

But then I got into a bit of a Git muddle trying to recreate it and put it to one side.

I'll get back to it today.

**Comment by matthewpersico** [comment]
Just the thought of you editing without a branch gave me the shivers. 🤣

**Pull request closed without merging**
