### PR TITLE
Make page.tt mobile friendly

### PR DESCRIPTION
**Pull request by mperry2**
This is my first attempt to address issue #83 and make the Perl Weekly issues mobile friendly. I'd like to get some feedback before I make changes to the other templates.

### CODE REVIEW

**Comment by szabgab** [comment]
Have you tried sending an e-mail to yourself using this? If yes, in what e-mail client have you checked it?
If no, then please try it.

**Comment by mperry2** [comment]
I haven't, but I will test it today with some email clients and report back with my findings.

**Comment by mperry2** [comment]
Well, that was a learning experience. I tested in Gmail, Outlook 2010, and Thunderbird. The email doesn't look that great in any of them. I've learned that email clients each support a different subset of CSS.

I'm going to close this pull request. I need to go back and fix things to leave the emailed newsletter the same as it is now. I'll submit another PR when I have a better solution.

**Comment by szabgab** [comment]
Originally I copied the layout from the JavaScript weekly assuming they know a lot more about this stuff than I do. That's where the tables came from!

**Pull request closed without merging**
